services:
  - type: web
    name: deepgen-ai-service
    runtime: image
    dockerfilePath: ./backend-ai-service/Dockerfile
    envVars:
      - key: TAVUS_API_KEY
        sync: false
      - key: TAVUS_REPLICA_ID
        sync: false
      - key: PUBLIC_BASE_URL
        value: https://deepgen-ai.onrender.com
    healthCheckPath: /health
